### ISSUE TITLE
Setup VSCode

### ISSUE THREAD

**Issue by Jesrogers** [elainetsun/meal-planning-app#29]
To help make code formatting standardized, plz install VSCode and download the ESLint & Prettier extensions. Once those extensions have been added, configure them in the following ways:

**Prettier**
-Check the "[Require Config](https://gyazo.com/0ae14ba67f9e644f766249ebb72573f1)" setting.

**ESLint**
-Enter the "[Working Directories](https://gyazo.com/0804af1a0415d8d5dec88312535329be)" setting for ESLint and add [this](https://gyazo.com/16c696b0ac7e66289795985cafbecc82) line to the JSON file: `"meal-planning"`.

After doing that, restart VSCode and verify that they work.

File > Preferences is how I access settings in VSCode, may be in another dropdown for you since I'm on a PC. Lemme know if you run into any trouble.

**Comment by michelletsun** [comment]
installed, everything works!
