### ISSUE TITLE
Add Search functionality 

### ISSUE THREAD

**Issue by elainetsun** [elainetsun/meal-planning-app#4]
Add a search bar to the top of the /recipes page. Should filter on recipe name and tags. 
Example of tags: gluten free, spicy, fast, etc.

**Comment by elainetsun** [comment]
@michelletsun can you add the search bar to the app toolbar?

**Comment by michelletsun** [comment]
do you mean add a search bar to the purple toolbar on the top? Like maybe the top right, similar style to the recipe search bar?

**Comment by elainetsun** [comment]
yeah thats what I meant before but what we have now is fine. we can come back to this later
